openapi: 3.0.0
info:
  title: PowerPoint Writer API
  description: API for writing LLM outputs into PowerPoint slides.
  version: 1.0.0
servers:
  - url: https://flask-powerpoint-api.onrender.com/create-slide
paths:
  /create-slide:
    post:
      summary: Create a new PowerPoint slide with content
      description: Takes input text and creates a new slide in a PowerPoint presentation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the slide
                content:
                  type: string
                  description: Main content for the slide
                presentationId:
                  type: string
                  description: ID of the PowerPoint presentation
                slideLayout:
                  type: string
                  description: Layout for the slide (e.g., "Title and Content", "Blank")
                  default: "Title and Content"
              required:
                - title
                - content
                - presentationId
      responses:
        200:
          description: Slide created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  slideId:
                    type: string
                    description: ID of the created slide
        400:
          description: Invalid input
        500:
          description: Server error
  /download-presentation:
    get:
      summary: Download the PowerPoint presentation
      description: Returns the PowerPoint file for the given presentation ID.
      parameters:
        - name: presentationId
          in: query
          required: true
          schema:
            type: string
          description: ID of the PowerPoint presentation
      responses:
        200:
          description: PowerPoint file retrieved successfully
          content:
            application/vnd.openxmlformats-officedocument.presentationml.presentation:
              schema:
                type: string
                format: binary
        404:
          description: Presentation not found
        500:
          description: Server error
s